# Generated by Django 4.0.3 on 2022-03-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_category_pages_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': ' Page', 'verbose_name_plural': ' Pages'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': ' Post', 'verbose_name_plural': ' Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': ' Tag', 'verbose_name_plural': ' Tags'},
        ),
        migrations.AlterField(
            model_name='pages',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_images'),
        ),
    ]
