# Generated by Django 4.0.3 on 2022-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_category_options_alter_pages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='search_engine_visibility',
            field=models.BooleanField(default=False, help_text='Discourage search engines from indexing this page', verbose_name='Search engine visibility'),
        ),
        migrations.AddField(
            model_name='posts',
            name='search_engine_visibility',
            field=models.BooleanField(default=False, help_text='Discourage search engines from indexing this post', verbose_name='Search engine visibility'),
        ),
    ]
