# Generated by Django 4.0.3 on 2022-03-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0003_alter_category_options_alter_pages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_title', models.CharField(blank=True, max_length=300, null=True)),
                ('blog_posts_show', models.IntegerField(blank=True, default=10, null=True)),
                ('blog_display', models.ManyToManyField(blank=True, to='contents.posts')),
                ('home_display', models.ManyToManyField(blank=True, to='contents.pages')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_title', models.CharField(blank=True, max_length=300, null=True)),
                ('site_title', models.CharField(blank=True, max_length=300, null=True)),
                ('tagline', models.CharField(default='Another Django Website', max_length=300)),
                ('site_url', models.CharField(blank=True, max_length=300, null=True)),
                ('admininstration_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('membership', models.BooleanField(default=False, help_text='anyone can reigister?')),
                ('search_engine_visibility', models.BooleanField(default=False, help_text='Discourage search engines from indexing this site', verbose_name='Search engine visibility')),
                ('site_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='settings.sitelanguage')),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tz', to='settings.timezone')),
            ],
        ),
    ]
