# Generated by Django 4.0.3 on 2022-03-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0003_alter_category_options_alter_pages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=300)),
                ('display_location', models.CharField(choices=[('page-menu', 'Page Menu'), ('sidebar-menu', 'Sidebar Menu'), ('footer-menu', 'Footer Menu'), ('social-media-menu', 'Social Media Menu')], max_length=20)),
                ('menu_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('menu_links', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.pages')),
            ],
        ),
    ]
