# Generated by Django 4.0.3 on 2022-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_category_options_alter_pages_options_and_more'),
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.RemoveField(
            model_name='menus',
            name='menu_links',
        ),
        migrations.AddField(
            model_name='menus',
            name='menu_links',
            field=models.ManyToManyField(blank=True, null=True, to='contents.pages'),
        ),
    ]
