# Generated by Django 4.0.3 on 2022-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_category_options_alter_pages_options_and_more'),
        ('appearance', '0002_alter_menus_options_remove_menus_menu_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menu_links',
            field=models.ManyToManyField(blank=True, to='contents.pages'),
        ),
    ]
